import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages"
import { drizzle } from "drizzle-orm/d1"

// @ts-ignore - the server build file is generated by `remix vite:build`
import * as build from "../build/server"

export const onRequest = createPagesFunctionHandler({
  // @ts-ignore - the server build file is generated by `remix vite:build`
  build,
  getLoadContext: async (context) => {
    const DB = drizzle(context.context.cloudflare.env.DB as D1Database)

    return {
      DB,
      env: context.context.cloudflare.env,
    }
  },
})
